apiVersion: v1
kind: PersistentVolume
metadata:
  name: openlsp-pv-filesystem-cln-server
  namespace: openlsp
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/k8s/pv/cln-server
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: openlsp-pv-filesystem-cln-client
  namespace: openlsp
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/k8s/pv/cln-client
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

