apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoind
  namespace: bitcoind
  labels:
    app.kubernetes.io/name: bitcoind
spec:
  capacity:
    storage: 1024Gi
  hostPath:
    path: /srv/kube-bitcoin-stack/bitcoind
    type: ""
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
