apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind
  namespace: bitcoind
  labels:
    app.kubernetes.io/name: bitcoind 
spec:
  storageClassName: ""
  volumeName: bitcoind
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "1024Gi"
