apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoin-pv-filesystem-bitcoind
  namespace: bitcoind
  labels:
    app.kubernetes.io/name: bitcoind
spec:
  capacity:
    storage: 750Gi
  hostPath:
    path: /srv/blockchain
    type: ""
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
