apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-pvc-bitcoind
  namespace: bitcoind
  labels:
    app.kubernetes.io/name: bitcoind 
spec:
  storageClassName: ""
  volumeName: bitcoin-pv-filesystem-bitcoind
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "750Gi"
