apiVersion: v1
kind: Secret
metadata:
  name: bitcoind-rpcpassword
  namespace: bitcoind
  labels:
    app.kubernetes.io/name: bitcoind
    app.kubernetes.io/part-of: kube-bitcoin-stack
stringData:
  password: tellnoone
  