apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: bitcoind-servicemonitor
  namespace: openlsp
  labels:
    app.kubernetes.io/name: bitcoind
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bitcoind
  podMetricsEndpoints:
  - port: metrics
