apiVersion: v1
kind: ConfigMap
metadata:
  name: lnd
  namespace: lnd
  labels:
    app.kubernetes.io/name: lnd
    app.kubernetes.io/part-of: kube-bitcoin-stack
data:
  lnd.conf: |-
    wallet-unlock-password-file=/tmp/lnd-pass
    wallet-unlock-allow-create=true
    restlisten=0.0.0.0:8080
    rpclisten=0.0.0.0:10009
    listen=0.0.0.0:9735
    listen=[::1]:9736
    prometheus.listen=0.0.0.0:9092
    bitcoin.active=true
    bitcoin.node=neutrino
    bitcoind.rpcuser=rpcuser
    bitcoind.zmqpubrawblock=tcp://bitcoind:28332
    bitcoind.zmqpubrawtx=tcp://bitcoind:28333
    tlsextradomain=lnd
    accept-keysend=1
    allow-circular-route=1
    stagger-initial-reconnect=1
    protocol.wumbo-channels=1
    maxchansize=500000000
    bitcoin.timelockdelta=60
    default-remote-max-htlcs=50
    debuglevel=info
    prometheus.enable=1
    gc-canceled-invoices-on-the-fly=true
    gc-canceled-invoices-on-startup=true
    tor.active=true
    tor.v3=true
    tor.skip-proxy-for-clearnet-targets=true
    tlsextradomain=lnd
    bitcoin.mainnet=true
        
    [neutrino]
    neutrino.connect=btcd0.lightning.engineering
    neutrino.useragentname=kube-bitcoin-stack


