apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bitcoind-servicemonitor
  namespace: lnd
  labels:
    release: kube-prom-stack
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lnd
  endpoints:
  - port: metrics
    interval: 10s
    path: /metrics
