apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-pvc-lnd
  namespace: lnd
  labels:
    app.kubernetes.io/name: lnd
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  storageClassName: ""
  volumeName: bitcoin-pv-filesystem-lnd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "10Gi"
