apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openlsp-pvc-lnd
  namespace: openlsp
spec:
  storageClassName: ""
  volumeName: openlsp-pv-filesystem-lnd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "10Gi"
