---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lnd
  namespace: lnd
  labels:
    app.kubernetes.io/name: lnd
    app.kubernetes.io/part-of: kube-bitcoin-stack
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch", "delete"]
