---
apiVersion: v1
kind: Secret
metadata:
  name: network
  namespace: lnd
  labels:
    app.kubernetes.io/part-of: kube-bitcoin-stack
    app.kubernetes.io/name: lnd
stringData:
  network: mainnet

---
apiVersion: v1
kind: Secret
metadata:
  name: lnd-pass
  namespace: lnd
  labels:
    app.kubernetes.io/name: lnd
    app.kubernetes.io/part-of: kube-bitcoin-stack
data:
  password: MWYyZDFlMmU2N2Rm
  