---
apiVersion: v1
kind: Service
metadata:
  name: lnd-p2p
  namespace: lnd
  labels:
    app.kubernetes.io/name: lnd
    app.kubernetes.io/part-of: kube-bitcoin  
spec:
  type: ClusterIP
  ports:
    - name: p2p
      port: 9735
  selector:
    app.kubernetes.io/name: lnd
    app.kubernetes.io/instance: release-name
