apiVersion: v1
kind: PersistentVolume
metadata:
  name: electrs
  namespace: electrs
  labels:
    app.kubernetes.io/name: electrs
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  capacity:
    storage: 750Gi
  hostPath:
    path: /srv/kube-bitcoin-stack/electrs
    type: ""
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
