apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: electrs
  namespace: electrs
  labels:
    app.kubernetes.io/name: electrs
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  storageClassName: ""
  volumeName: electrs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "150Gi"
