apiVersion: v1
kind: Service
metadata:
  name: electrs
  namespace: electrs
  labels:
    app: electrs
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  ports:
  - port: 50001
    name: electrum
    targetPort: 50001
  selector:
    app: electrs
