# apply with kubectl patch deployment ingress-nginx-controller --patch "$(cat ingress-nginx-controller-patch.yaml)" -n ingress-nginx
spec:
  template:
    spec:
      containers:
      - name: controller
        ports:
         - containerPort: 8333
           hostPort: 8333
