apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  8332: "openlsp/bitcoind:8332"
  8333: "openlsp/bitcoind:8333"

---
apiVersion: v1
kind: ConfigMap44
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  5353: "default/example-go:8080"
