# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fulcrum-ingress
#   namespace: fulcrum
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
# spec:
#   rules:
#   - host: fulcrum.example.com  # Replace with your domain
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: fulcrum
#             port:
#               number: 8080
#   - host: electrum.fulcrum.example.com  # Replace with your domain
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: fulcrum
#             port:
#               number: 50002