apiVersion: v1
kind: Service
metadata:
  name: fulcrum
  namespace: fulcrum
  labels:
    app: fulcrum
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  ports:
  - port: 50002
    name: electrum
    targetPort: 50002
  - port: 8080
    name: web
    targetPort: 8080
  selector:
    app: fulcrum