apiVersion: v1
kind: Service
metadata:
  name: fulcrum
  namespace: fulcrum
  labels:
    app: fulcrum
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  ports:
  - port: 50001
    name: electrum
    targetPort: 50001
  - port: 8080
    name: admin
    targetPort: 8080
  - port: 8081
    name: stats
    targetPort: 8081

  selector:
    app: fulcrum