apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fulcrum
  namespace: fulcrum
  labels:
    app: fulcrum
    app.kubernetes.io/part-of: kube-bitcoin-stack
spec:
  serviceName: "fulcrum"
  replicas: 1
  selector:
    matchLabels:
      app: fulcrum
  template:
    metadata:
      labels:
        app: fulcrum
    spec:
      containers:
        - name: fulcrum
          image: cculianu/fulcrum:latest
          command: ["Fulcrum", "/config/fulcrum.conf"]
          ports:
            - containerPort: 50001
              name: electrum
            - containerPort: 8080
              name: admin
            - containerPort: 8081
              name: stats
          volumeMounts:
            - name: fulcrum-data-dir
              mountPath: /data
            - name: fulcrum-config
              mountPath: /config/fulcrum.conf
              subPath: fulcrum.conf
          resources: {}
          readinessProbe:
            tcpSocket:
              port: electrum
            initialDelaySeconds: 36000
            periodSeconds: 30
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: stats
            periodSeconds: 10
            initialDelaySeconds: 36000
            failureThreshold: 2
      volumes:
        - name: fulcrum-data-dir
          persistentVolumeClaim:
            claimName: fulcrum
        - name: fulcrum-config
          configMap:
            name: fulcrum-config
